services:
  fitness_db:
    image: postgres:13
    container_name: fitness_db
    environment:
      POSTGRES_USER: fitness_user
      POSTGRES_PASSWORD: fitness_password
      POSTGRES_DB: fitness_db
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trackr_app
    ports:
      - '8098:8098'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://fitness_db:5432/fitness_db
      SPRING_DATASOURCE_USERNAME: fitness_user
      SPRING_DATASOURCE_PASSWORD: fitness_password
    depends_on:
      - fitness_db

volumes:
  postgres-data:
